

-- DA DODATE JOS SAMO UMESTO  1,2,3 DODATE SLEDECI REDNI BROJ ZONE! HVALA!
CREATE TABLE IF NOT EXISTS `zone` (
  `brojzone` tinyint(50) DEFAULT NULL,
  `owner` text DEFAULT NULL,
  `zauzimase` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*!40000 ALTER TABLE `zone` DISABLE KEYS */;
REPLACE INTO `zone` (`brojzone`, `owner`, `zauzimase`) VALUES
	(1, 'niko', 0),
	(2, 'niko', 0),
	(3, 'niko', 0);
/*!40000 ALTER TABLE `zone` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
